import type { RorschachResponse } from "@/types/rorschach";

export const sampleResponses: RorschachResponse[] = [
  {
    response_index: 1,
    card: "I",
    location: "W",
    dq: "o",
    determinants: ["F"],
    fq: "o",
    pair: false,
    FrScore: false,
    rFScore: false,
    contents: ["A"],
    popular: true,
    z: "ZW",
    special_scores: [],
    zscore: 1,
    gphr: "",
  },
  {
    response_index: 1,
    card: "II",
    location: "D",
    dq: "o",
    determinants: ["F"],
    fq: "u",
    pair: true,
    FrScore: false,
    rFScore: false,
    contents: ["A"],
    popular: false,
    z: "",
    special_scores: [],
    gphr: "",
  },
  {
    response_index: 1,
    card: "III",
    location: "Dd",
    dq: "o",
    determinants: ["F"],
    fq: "o",
    pair: true,
    FrScore: false,
    rFScore: false,
    contents: ["An"],
    popular: false,
    z: "",
    special_scores: [],
    gphr: "",
  },
  {
    response_index: 1,
    card: "IV",
    location: "W",
    dq: "o",
    determinants: ["F"],
    fq: "u",
    pair: false,
    FrScore: false,
    rFScore: false,
    contents: ["A"],
    popular: false,
    z: "ZW",
    special_scores: [],
    zscore: 2,
    gphr: "",
  },
  {
    response_index: 1,
    card: "V",
    location: "W",
    dq: "o",
    determinants: ["FMa"],
    fq: "o",
    pair: false,
    FrScore: false,
    rFScore: false,
    contents: ["A"],
    popular: true,
    z: "ZW",
    special_scores: [],
    zscore: 1,
    gphr: "",
  },
  {
    response_index: 1,
    card: "VI",
    location: "W",
    dq: "o",
    determinants: ["FMp"],
    fq: "u",
    pair: false,
    FrScore: false,
    rFScore: false,
    contents: ["A"],
    popular: true,
    z: "ZW",
    special_scores: [],
    zscore: 2.5,
    gphr: "",
  },
  {
    response_index: 1,
    card: "VII",
    location: "D",
    dq: "+",
    determinants: ["Ma"],
    fq: "o",
    pair: false,
    FrScore: false,
    rFScore: false,
    contents: ["(H)"],
    popular: true,
    z: "ZD",
    special_scores: ["GHR"],
    zscore: 3,
    gphr: "GHR",
  },
  {
    response_index: 1,
    card: "VIII",
    location: "D",
    dq: "o",
    determinants: ["FC", "FY"],
    fq: "o",
    pair: true,
    FrScore: false,
    rFScore: false,
    contents: ["A"],
    popular: true,
    z: "",
    special_scores: [],
    gphr: "",
  },
  {
    response_index: 1,
    card: "IX",
    location: "D",
    dq: "o",
    determinants: ["FC"],
    fq: "-",
    pair: false,
    FrScore: false,
    rFScore: false,
    contents: ["Ge"],
    popular: false,
    z: "",
    special_scores: [],
    gphr: "",
  },
  {
    response_index: 1,
    card: "X",
    location: "DdS",
    dq: "o",
    determinants: ["CF"],
    fq: "u",
    pair: false,
    FrScore: false,
    rFScore: false,
    contents: ["A"],
    popular: false,
    z: "",
    special_scores: [],
    gphr: "",
  },
  {
    card: "I",
    response_index: 2,
    location: "D",
    dq: "o",
    determinants: ["F"],
    fq: "o",
    pair: false,
    FrScore: false,
    rFScore: false,
    contents: ["Ad"],
    popular: false,
    z: "",
    special_scores: [],
    gphr: "",
  },
  {
    card: "II",
    response_index: 2,
    location: "D",
    dq: "o",
    determinants: ["F"],
    fq: "u",
    pair: false,
    FrScore: false,
    rFScore: false,
    contents: ["An"],
    popular: false,
    z: "",
    special_scores: [],
    gphr: "",
  },
  {
    card: "V",
    response_index: 2,
    location: "W",
    dq: "o",
    determinants: ["FMa"],
    fq: "o",
    pair: false,
    FrScore: false,
    rFScore: false,
    contents: ["A"],
    popular: true,
    z: "ZW",
    special_scores: [],
    gphr: "",
    zscore: 1,
  },
  {
    card: "V",
    response_index: 3,
    location: "W",
    dq: "o",
    determinants: ["F"],
    fq: "u",
    pair: false,
    FrScore: false,
    rFScore: false,
    contents: ["Cg", "H"],
    popular: false,
    z: "ZW",
    special_scores: ["GHR", "PER"],
    gphr: "GHR",
    zscore: 1,
  },
  {
    card: "VII",
    response_index: 2,
    location: "DS",
    dq: "o",
    determinants: ["FC'"],
    fq: "o",
    pair: true,
    FrScore: false,
    rFScore: false,
    contents: ["Sc", "Hh", "Hd"],
    popular: true,
    z: "ZS",
    special_scores: ["PER", "GHR"],
    gphr: "GHR",
    zscore: 4,
  },
];
